### ISSUE TITLE
I can't figure out how to use this

### ISSUE THREAD

**Issue by bbigras** [mnacamura/nixpkgs-cdda-mods#1]
I added the overlay but I can't figure it out. I'm using it with home-manager.

```nix
  home.packages = [
    cataclysm-dda.withMods (mods: with mods; [
      tileset.UndeadPeople
      soundpack.atmark
    ])
  ];
```

```
error: attribute 'withMods' missing, at /home/bbigras/nix-cfg/desktop/home.nix:35:5
(use '--show-trace' to show detailed location information)
```

**Comment by mnacamura** [comment]
This overlay depends on NixOS/nixpkgs/pull/84873, which is yet to be merged.

**Comment by bbigras** [comment]
Oh. Thank you very much.

**Comment by bbigras** [comment]
Not that the PR is merged, will this overlay be used to have fresh mods automatically updated every day like the [emacs overlay](https://github.com/nix-community/emacs-overlay)?

**Comment by mnacamura** [comment]
Could be. I think one practical solution is to automatically generate nix expressions from CDDA Game Launcher's  [mods.json](https://github.com/remyroy/CDDA-Game-Launcher/blob/master/data/mods.json) as it is well maintained.

**Comment by bbigras** [comment]
That would be awesome.

**Comment by mnacamura** [comment]
I've made some commits to generate nix expressions from CDDA Game Launcher's JSON data. For the moment, only soundpacks are available in this overlay. try it out if interested.

**Comment by bbigras** [comment]
The overlay seems to work thanks!

Maybe it could be nice to have a cachix cache for this project. I wonder if it would work no mater which tileset and sound pack people choose.
